### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by inesarmadabras** [mjhea0/passport-social-auth#4]
I'm doing everything [step-by-step](http://mherman.org/blog/2015/09/26/social-authentication-in-node-dot-js-with-passport/#.WGzjuLGtG-o)  but, when I do the first Sanity Check I get this errors:

```
Mac-mini-de-xxx:passport-social-auth-1 xxx$  npm start

> _example@0.0.0 start /Users/xxx/Desktop/passport-social-auth-1
> node ./server/bin/www

module.js:474
    throw err;
    ^

Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/Desktop/passport-social-auth-1/server/app.js:4:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! _example@0.0.0 start: `node ./server/bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the _example@0.0.0 start script 'node ./server/bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the _example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs _example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls _example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Desktop/passport-social-auth-1/npm-debug.log
```

**It's the same with the final code. After this,  I ran `npm install` and then `npm start` again.
And now I've another error:**

```
Mac-mini-de-xxx:passport-social-auth-1 xxx$ npm start

> _example@0.0.0 start /Users/xxx/Desktop/passport-social-auth-1
> node ./server/bin/www

Listening on port 3000

/Users/xxx/Desktop/passport-social-auth-1/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! _example@0.0.0 start: `node ./server/bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the _example@0.0.0 start script 'node ./server/bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the _example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs _example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls _example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Desktop/passport-social-auth-1/npm-debug.log
Mac-mini-de-xxx:passport-social-auth-1 xxx$  npm start 
```

**Any thoughts?**

**Comment by inesarmadabras** [comment]
It was a mongod problem!
The dbPath must exist before you start mongod. 

A easy way to solve is copy the **db** folder (from mongodb) to the root, and then , in a new terminal, run ` mongod --dbpath db`   ,  to store data files at an other path.

+info: https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes

db folder: https://github.com/inesarmadabras/mongodb-start
